services:
  vm_manager:
    container_name: vm_manager
    image: python:3.12.4
    ports:
      - "8000:8000"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - "5432:5432"

volumes:
  postgres_data: