services:
  vm_manager:
    image: python:3.12.4
    command: python server_side/launch.py
    ports:
      - "8000:8000"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
volumes:
  postgres_data: